### ISSUE TITLE
Abnormal color

### ISSUE THREAD

**Issue by yyy33** [catppuccin/nvim#182]
Hello, my line number and the color of the current line and the current column seem to be displayed abnormally, the terminal I use is xterm, how should I set it?

![2022-07-13_20-23](https://user-images.githubusercontent.com/51548147/178732617-84eb36fc-9e32-4b21-8983-a4a953f706a2.png)

**Comment by yyy33** [comment]
> Hmm I don't have this issue on xterm. Maybe you didn't set your `~/.Xresources` color correctly?
> 
> Are you using tmux? Check your color configuration

I'm also using tmux, how should I set the color of tmux or xterm to use this theme properly

**Comment by nullchilly** [comment]
What's the output of `echo $TERM`?

**Comment by EdenEast** [comment]
By default tmux says to your terminal that it is `screen` without 256 color support. In your tmux config make sure to set the default terminal value to 256.

```
set -g default-terminal "screen-256color"
```

In your `.Xresources` set your terminal name to to state 256 color

```
XTerm*termName: xterm-256color
```

**Comment by yyy33** [comment]
> echo $TERM

The value is `xterm-256color`,This value is always the same whether I open tmux or not

**Comment by nullchilly** [comment]
@yyy33 The value should not be the same when you open tmux, it should be `tmux-256color` instead. **Do not** set the TERM variable from your ~/.bashrc or ~/.bash_profile or similar file. The terminal itself should report the correct TERM to the system so that the proper terminfo file will be used.

Edit `~/.Xresources` and add the line `XTerm.termName: xterm-256color`. Then run `xrdb merge ~/.Xresources &` in your terminal.

Please read through https://wiki.archlinux.org/title/Xterm#Configuration this is not an issue with the colorscheme and you should make some effort on your end

**Comment by nullchilly** [comment]
I have added this in the [readme section](https://github.com/catppuccin/nvim/tree/dev#abnormal-colors)
