### ISSUE TITLE
Update pain

### ISSUE THREAD

**Issue by axieax** [catppuccin/nvim#207]
Hi, updating this plugin has always been a pain (through packer.nvim -> manually git reset and pull) due to the rebasing / forced commit overwrites. I understand that there is a dev branch, but is it possible to merge this back into main without rewriting non-related commits? I'm not sure what the cause of this is, since even when trying out the dev branch today, do I find myself having to force update every single time.

**Comment by Pocco81** [comment]
Heya! Both `main` and `dev` are equally up to date with each other, so you should be able to seamlessly transition between one another if you wish so.

Speaking of Packer (and really any other package manager) breaking down: read #178 point number one. 

This was also mentioned in our Discord server. Yes it was out fault here because we had to amend a commit to clarify it had breaking changes, but still, I believe package managers such as Packer should have some sort of default action that they could perform if things like these were to happen (e.g. doing a reset or a rebase).

Either way this could've been avoided, so I apologize for any inconveniences caused. Hope everything is good now :)

**Comment by nullchilly** [comment]
@axieax You need to add a colon to update hook, like this: `run = ":CatppuccinCompile"`. I am sorry :<

**Comment by axieax** [comment]
@nullchilly thanks for letting me know!
