### ISSUE TITLE
I like to have docker setup so that I can have preview of the workflow before installing in my main machine.

### ISSUE THREAD

**Issue by coderj001** [catppuccin/nvim#306]
**Is your feature request related to a problem? Please describe.**
When i try to checkout different nvim config some thing don’t go well due to requirement or missing packages. So i like to have have a preview of the nvim config and it workflow, is it really that i needed or not. And I have to install and uninstall those requirements manually every-time to is frustrating, also on my main machine in need to do my daily chores. I think many of developers face same issue.

**Describe the solution you'd like**
Adding docker, one can build docker image and check it out local with out interfaring with main machine. Or even better having docker image on docker hub just download use.

@emxxjnm if you like my idea i can take upon the task.

**Comment by nekowinston** [comment]
Hi there. :wave:
I have to vote against this feature request. IMO this is out of scope for this repository, because it is a colorscheme.

> When i try to checkout different nvim config

This is not a Neovim config. It's a very extensible colorscheme with many integrations.
Which integrations should we add? Lualine or Feline? Nvimtree or Neotree? Bufferline or BarBar?

> And I have to install and uninstall those requirements manually every-time to is frustrating, also on my main machine in need to do my daily chores.

You can already install most neovim configs into a temporary location, and as long as those dotfiles use the [Packer Bootstrap](https://github.com/wbthomason/packer.nvim#bootstrapping), everything is installed for you, in a temporary location. You don't need system packages in most cases.
For example if you wanted to clone @Pocco81's [dotfies](https://github.com/pocco81/.dots):
```bash
export XDG_CONFIG_HOME=/tmp XDG_DATA_HOME=/tmp XDG_CACHE_HOME=/tmp && rm -rf /tmp/nvim && svn export https://github.com/Pocco81/.dots/trunk/dots/.config/nvim /tmp/nvim && nvim -nu /tmp/nvim/init.lua
```
(note that this snippet requires `svn`)

> Or even better having docker image on docker hub just download use.

I personally offer my [dotfiles as a Docker image](https://github.com/nekowinston/dotfiles/pkgs/container/dotfiles%2Fdotfiles), and it's a pain to maintain for the reasons mentioned above. I only build them every once in a while. I'm not against **us linking to a 3rd party repo** which offers a "showcase docker image", but again, I am against including this here.

**Comment by coderj001** [comment]
@nekowinston now I think about it yeah it's just a color scheme no need to add complication. Thank you for the feedback.
