### ISSUE TITLE
Would base16 support be possible? (for overwriting colors)

### ISSUE THREAD

**Issue by Mateiadrielrafael** [catppuccin/nvim#400]
**Is your feature request related to a problem? Please describe.**
I was wondering if there is a way to use this theme as a generic base16 nvim theme generator. I have tried a bunch of (n)vim plugins for base16 based theming, but none of them have integrations as good as this one. I know there is already a way to overwrite colors, but it requires some extra colors which I'm not sure how to generate. 

**Describe the solution you'd like**
I guess I'd like an explanation on how (if at all possible) to generate the remaining colors programmatically.

**Describe alternatives you've considered**
Using different theme plugins based on what my current base16 theme name is. I already do this, but it would be nice if I wouldn't have to.

**Additional context**
I use nix, although I don't think that matters for the solution. The reason I am asking is because the catppuccin discord theme seems to have different subvariants with different accent colors. I am not sure how to mirror that kind of thing to the rest of my system.

**Comment by nullchilly** [comment]
You might be interested in [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim) as it follows base16 convention and along with [nvchad fork of base16](https://github.com/NvChad/base46/tree/master/lua/base46/themes) as it supports many different themes.

Unfortunately I don't have the time to adopt this in catppuccin, contributions are greatly appreciated!

Also this was on my mind for a long time, a colorscheme framework that **just works** with given palette and automatic plugin integrations with an ability to correct itself for more visual appealing (Inspired after colorblind mode was [introduced in nightfox](https://github.com/EdenEast/nightfox.nvim#how-does-this-work).

![](https://imgs.xkcd.com/comics/standards.png)

This is straight out of novelty and (probably) needs to train an AI in order to stay relevant at all or find a magical algorithm to generate different subvariants with different accent colors **beautifully**

**Comment by Pocco81** [comment]
Aside from what @nullchilly mentioned, I'll also add that it's not possible to make a Catppuccin version that follows [base16 standards](https://github.com/chriskempson/base16/blob/main/builder.md), mainly because we have more than 16 colors and the way we handle them is a bit different from what Base16 states.
