### ISSUE TITLE
statusbar colors for Quickfix List mode is unreadable with latte variant

### ISSUE THREAD

**Issue by sdemura** [catppuccin/nvim#494]
### Description

<img width="912" alt="image" src="https://github.com/catppuccin/nvim/assets/11758459/af666d60-4de4-4766-b64e-f1f22b488879">

### Neovim version

```markdown
nvim 0.9
```

### Terminal and multiplexer

alacritty + tmux, iterm2 no tmux

### Catppuccin version / branch / rev

head

### Steps to reproduce

Use latte variant

### Expected behavior

Quickfix list status indicator should be readable. Bright blue color with white text is jarring.

### Actual behavior

Bright blue text, white background on quickfix list status indicator

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin-latte")
-- add anything else here
```

**Comment by nullchilly** [comment]
Can't reproduce

![image](https://github.com/catppuccin/nvim/assets/56817415/10cfd744-b304-4594-bf19-2a702e2d225d)

**Comment by nullchilly** [comment]
According to [lazy.nvim#colorschemes](https://github.com/folke/lazy.nvim#-colorschemes), since start plugins can possibly change existing highlight groups, it's important to make sure that your main colorscheme is loaded first. To ensure this you can use the `priority=1000` field, so add this to your config.

```lua
	{
		"catppuccin/nvim",
		name = "catppuccin",
		lazy = false,
		priority = 1000, --[[ ADD THIS LINE ]]
		config = function()
			require("catppuccin").setup({
				integrations = {
					mini = true,
					neotree = false,
					mason = true,
					treesitter = true,
					hop = true,
					indent_blankline = {
						enabled = true,
					},
					native_lsp = { enabled = true },
					-- barbecue = {
					--     bold_basename = true,
					-- }
				},
			})
			vim.cmd("colorscheme catppuccin-latte")
		end,
	}
```

# Before

50% chance of getting unreadable Quickfix list:

https://github.com/catppuccin/nvim/assets/56817415/5bbde235-0f24-403a-aea9-6fbe60988b28

# After

No issue after adding `priority=1000`

https://github.com/catppuccin/nvim/assets/56817415/3f7feb10-3217-42be-be2e-8c9ca0e6150a
