### ISSUE TITLE
Bad contrast with neogit integration

### ISSUE THREAD

**Issue by bomgar** [catppuccin/nvim#627]
### Description

The contrast of text on active blocks (block where the cursor is) is bad.

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1702233742
```

### Terminal and multiplexer

wezterm 20230712-072601-f4abf8fd

### Catppuccin version / branch / rev

64dc309

### Steps to reproduce

Open neogit in a git repo with changes and history. `:Neogit`

### Expected behavior

Text should have better contrast.

### Actual behavior

![2023-12-15-110256_grim](https://github.com/catppuccin/nvim/assets/402052/db7a9e98-c431-45fa-b7db-601a0eac0d33)
![2023-12-15-110248_grim](https://github.com/catppuccin/nvim/assets/402052/4efd3537-1f53-4d92-8c6d-73730fddd72c)

This does not happen if I set `neogit = false` in my catppuccin config.

**The cursor position is important. If I move the cursor to somewhere else it looks good.**

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "catppuccin/nvim",
    "nvim-lua/plenary.nvim",
    {"NeogitOrg/neogit", opts={}},
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")

-- add anything else here
```

**Comment by nullchilly** [comment]
I believe this bug was introduced in #614

<table>
<tr>
<td></td> <td> Mocha </td> <td> Latte </td>
</tr>
<tr>

<td>

# Before

</td>

<td>

![image](https://github.com/catppuccin/nvim/assets/56817415/905eae29-e75a-4bca-9c6d-a59cc10bd969)

</td>
<td>

![image](https://github.com/catppuccin/nvim/assets/56817415/455b3c9d-ad46-4357-9c02-37e8c96490a4)

</td>
</tr>

<tr>

<td>

# After

</td>

<td>

![image](https://github.com/catppuccin/nvim/assets/56817415/ea80a886-3c6a-4de7-80e4-fe57f8d38b3f)

</td>
<td>

![image](https://github.com/catppuccin/nvim/assets/56817415/670f6db5-2981-4fe5-a2e3-191d6efb9d11)

</td>
</tr>

</table>

I pushed an update, can you try it out?

**Comment by bomgar** [comment]
Perfect. Thank you.
