### ISSUE TITLE
Additional dim_inactive option for transparent setups

### ISSUE THREAD

**Issue by Lord-Leonard** [catppuccin/nvim#673]
**Is your feature request related to a problem? Please describe.**
When I set up a transparent setup, I don't like the way inactive windows are displayed. I find it especially hard to make out a popup. 
Therefore I would like to use the dim_inactive option. But I, again don't like the harsh contrast between my transparent popup and the now hard background. 

_without dim_
![image](https://github.com/catppuccin/nvim/assets/88632681/3a4a56d9-d2af-4f7a-8e6d-429160fcf2ab)
hard to spot

_with dim_
![image](https://github.com/catppuccin/nvim/assets/88632681/6127a044-6c17-417b-b2fd-fd84fe7e99ee)
this looks awkward as well

**Describe the solution you'd like**
I would like the background color of inactive windows to still be transparent, but just a little more saturated. 

**Describe alternatives you've considered**
I tried lighten or darken or leaving it as is. I will probably keep dim_inactive off if I cant fix it somehow :/  
But I thought I might as well suggest the feature as I absolutely love the work you do and am willing to help make it happen <3

**Additional context**
I would LOVE this feature, as it would complete my setup in terms of color. 
I can dedicate time to development if someone points me in the right direction as to where I would even start :)

**Comment by vollowx** [comment]
@Lord-Leonard First of all, thanks for your love for this project! Unfortunately IMO this is technically impossible for us to implement, because the transparent background is achieved by setting the background to NONE, and what you can see is the raw background of the terminal. So, we are unable to make the transparent part look different - for the background there are only 2 choices:

1. colored and solid
2. color removed and transparent

we can't make it colored and transparent.

However, I would like to leave this issue open for the possibility that this may be achieved.

**Comment by jack-mil** [comment]
What about changing the saturation of the text foreground colors?
 I don't know about what is possible in nvim, but I do know that when I first tried the dim_inactive option, I actually assumed it would be affecting the foreground text color.
 I guess I am just used to having transparent background for everything.
