### ISSUE TITLE
Terminal colors do not work

### ISSUE THREAD

**Issue by hahuang65** [catppuccin/nvim#86]
Currently, terminal colors are not working.
Attached is a picture of nvim with a terminal, and my regular terminal emulator.
They are both set to use catppuccin color.

However, you will not that the terminal inside nvim is bust.
![catppuccin](https://user-images.githubusercontent.com/280972/148633741-a3b5f3d6-a34c-48e3-9cbb-4af2b8a6e460.png)

I have to manually set:
```
vim.g.terminal_color_0 = "#302D41"
vim.g.terminal_color_1 = "#DDB6F2"
vim.g.terminal_color_2 = "#ABE9B3"
vim.g.terminal_color_3 = "#FAE3B0"
vim.g.terminal_color_4 = "#96CDFB"
vim.g.terminal_color_5 = "#F5C2E7"
vim.g.terminal_color_6 = "#DDB6F2"
vim.g.terminal_color_7 = "#D9E0EE"
vim.g.terminal_color_8 = "#575268"
vim.g.terminal_color_9 = "#E8A2AF"
vim.g.terminal_color_10 = "#B5E8E0"
vim.g.terminal_color_11 = "#F8BD96"
vim.g.terminal_color_12 = "#89DCEB"
vim.g.terminal_color_13 = "#C9CBFF"
vim.g.terminal_color_14 = "#F5E0DC"
vim.g.terminal_color_15 = "#C3BAC6"
```

for the terminal colors to work properly. I'm not even sure that those are the right, and intended colors.

Is this something that could be implemented into the nvim plugin?

**Comment by kahnclusions** [comment]
It looks like those values _should_ be set here https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/utils/util.lua#L119-L137 but then if we look here https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/core/mapper.lua#L207-L209, it looks like it directly returns `color_palette` which just includes the colour definitions with names like rosewater, flamingo, but catppuccin1, catppuccin2 are nowhere to be found. So I'm guessing this is a small oversight that those values are simply never initialised properly.

The fix is probably just to add the mapping to `mapper.lua` but I'm not sure what the intended colours are for terminal.

**Comment by Pocco81** [comment]
My bad, I'd forgotten about updating that file after a breaking change which ended with the `catppuccin*` convention. I'll fix this ASAP.

**Comment by kahnclusions** [comment]
Thanks!

**Comment by hahuang65** [comment]
For me, this doesn't appear to be fixed. I removed my temporary configuration for the terminal colors, and pulled the latest.
I've attached a picture of my neovim terminal that shows that my plugin has the commit mentioned that should fix this.

![Screen Shot 2022-01-10 at 10 01 52 AM](https://user-images.githubusercontent.com/280972/148815865-cc1e540a-5dcb-4550-951e-94a2987e810f.png)

**Comment by Pocco81** [comment]
@hahuang65 there is a setting called `terminal_colors`. Did you enable it?

**Comment by hahuang65** [comment]
Thank you. That was it. It was set to false previously. This is my fault.

Thanks for your hard work and the amazing colorscheme!
